eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8085
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-feign
spring:
  application:
    name: service-zuul
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    rabbitmq:
      host: localhost
      password: guest
      port: 5672
      username: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



